"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { ArrowLeft, Clock } from 'lucide-react';

export default function IELTSReadingTest18_3() {
  const [showAnswers, setShowAnswers] = useState(false);
  const [timeLeft, setTimeLeft] = useState(60 * 60);
  const [activeTab, setActiveTab] = useState(0);

  useEffect(() => {
    if (timeLeft <= 0) return;
    const timer = setInterval(() => setTimeLeft(prev => prev - 1), 1000);
    return () => clearInterval(timer);
  }, [timeLeft]);

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60).toString().padStart(2, '0');
    const s = (seconds % 60).toString().padStart(2, '0');
    return `${m}:${s}`;
  };

  const inputClass = "inline-flex w-32 px-3 py-1.5 mx-2 bg-blue-50 border-2 border-blue-400 rounded-lg shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none text-slate-800 text-center font-bold transition-all hover:bg-blue-100";

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-slate-50">
      {/* Header */}
      <header className="flex h-16 items-center justify-between border-b border-slate-200/60 bg-white/80 backdrop-blur-md px-8 shadow-sm z-20">
        <div className="flex items-center">
          <Link href="/" className="mr-4 flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 hover:bg-slate-200 transition-colors shadow-sm">
            <ArrowLeft className="h-5 w-5 text-slate-700" />
          </Link>
          <h1 className="text-2xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-700 to-indigo-700 tracking-tight">Reading 18.3</h1>
        </div>
        <div className="flex items-center bg-slate-100/80 px-4 py-2 rounded-xl border border-slate-200 shadow-inner">
          <Clock className="w-5 h-5 text-slate-500 mr-3" />
          <span className="font-mono text-xl font-bold text-slate-700">{formatTime(timeLeft)}</span>
        </div>
      </header>

      {/* Main Layout */}
      <main className="flex flex-1 overflow-hidden relative p-6 gap-6">
        {/* Left Pane: Questions */}
        <section className="w-1/2 relative z-0 bg-white rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 overflow-y-auto scroll-smooth flex flex-col">
          <div className="p-10 prose prose-slate prose-p:mb-6 prose-headings:text-slate-800 prose-p:text-slate-700 max-w-none flex-1">
            {activeTab === 0 && (
              <div
                dangerouslySetInnerHTML={{
                  __html: `
<p style="text-align: justify;"><strong>Questions 1-4</strong><br />Reading Passage 1 has eight sections, A-H. Which section contains the following information? Write the correct letter, <strong>A-H</strong>, in boxes 1-4 on your answer sheet.</p>

<p style="text-align: justify;">
1. <input type="text" class="${inputClass}" /> an explanation of the industrial processes that create potential raw materials for concrete<br />
2. <input type="text" class="${inputClass}" /> a reference to the various locations where high-rise wooden buildings can be found<br />
3. <input type="text" class="${inputClass}" /> an indication of how widely available the raw materials of concrete are<br />
4. <input type="text" class="${inputClass}" /> the belief that more high-rise wooden buildings are needed before wood can be regarded as a viable construction material
</p>

<p style="text-align: justify;"><strong>Questions 5-8</strong><br />Complete the summary below. Choose <strong>ONE WORD ONLY</strong> from the passage for each answer. Write your answers in boxes 5-8 on your answer sheet.</p>

<p style="text-align: center;"><strong>Making buildings with wood</strong></p>
<p style="text-align: justify;">Wood is a traditional building material, but current environmental concerns are encouraging (5) <input type="text" class="${inputClass}" /> to use wood in modern construction projects. Using wood, however, has its challenges. For example, as (6) <input type="text" class="${inputClass}" /> in the atmosphere enters wood, it increases in size. In addition, wood is prone to pests and the risk of fire is greater. However, wood can be turned into a better construction material if it is treated and combined with other materials. In one process, (7) <input type="text" class="${inputClass}" /> of solid wood are glued together to create building blocks. These blocks are lighter than concrete and steel but equal them in strength. Experts say that wooden buildings are an improvement on those made of concrete and steel in terms of the (8) <input type="text" class="${inputClass}" /> with which they can be constructed and how much noise is generated by the process.</p>

<p style="text-align: justify;"><strong>Questions 9-13</strong><br />Look at the following statements (Questions 9-13) and the list of people below. Match each statement with the correct person, <strong>A, B, C or D</strong>. Write the correct letter, A, B, C or D, in boxes 9-13 on your answer sheet. NB You may use any letter more than once.</p>

<p style="text-align: justify;">
9. <input type="text" class="${inputClass}" /> The environmental advantage of cement alternatives may not be as great as initially assumed.<br />
10. <input type="text" class="${inputClass}" /> It would be hard to create a construction alternative to concrete that offers so many comparable benefits.<br />
11. <input type="text" class="${inputClass}" /> Worries about the environment have led to increased interest in wood as a construction material.<br />
12. <input type="text" class="${inputClass}" /> Expense has been a factor in the negative response to the development of new cements.<br />
13. <input type="text" class="${inputClass}" /> The environmental damage caused by concrete is due to it being produced in large quantities.
</p>

<p style="text-align: justify;"><strong>List of People</strong><br />
<strong>A</strong> Chris Cheeseman<br />
<strong>B</strong> Markus Mannstrom<br />
<strong>C</strong> Anna Surgenor<br />
<strong>D</strong> Felix Preston and Johanna Lehne</p>
`
                }}
              />
            )}

            {activeTab === 1 && (
              <div
                dangerouslySetInnerHTML={{
                  __html: `
<p style="text-align: justify;"><strong>Questions 14-20</strong><br />Reading Passage 2 has seven paragraphs, A-G. Choose the correct heading for each paragraph from the list of headings below. Write the correct number, <strong>i-viii</strong>, in boxes 14-20 on your answer sheet.</p>

<p style="text-align: justify;"><strong>List of Headings</strong><br />
<strong>i</strong> A period in cold conditions before the technology is assessed<br />
<strong>ii</strong> Marketing issues lead to failure<br />
<strong>iii</strong> Good and bad aspects of steam technology are passed on<br />
<strong>iv</strong> A possible solution to the issues of today<br />
<strong>v</strong> Further improvements lead to commercial orders<br />
<strong>vi</strong> Positive publicity at last for this quiet, clean, fast vehicle<br />
<strong>vii</strong> A disappointing outcome for customers<br />
<strong>viii</strong> A better option than the steam car arises</p>

<p style="text-align: justify;">
14. <input type="text" class="${inputClass}" /> Paragraph A<br />
15. <input type="text" class="${inputClass}" /> Paragraph B<br />
16. <input type="text" class="${inputClass}" /> Paragraph C<br />
17. <input type="text" class="${inputClass}" /> Paragraph D<br />
18. <input type="text" class="${inputClass}" /> Paragraph E<br />
19. <input type="text" class="${inputClass}" /> Paragraph F<br />
20. <input type="text" class="${inputClass}" /> Paragraph G
</p>

<p style="text-align: justify;"><strong>Questions 21-23</strong><br />Choose the correct letter, <strong>A, B, C or D</strong>.</p>

<p style="text-align: justify;">
21. <input type="text" class="${inputClass}" /> What point does the writer make about the steam car in Paragraph B?<br />
<strong>A</strong> Its success was short-lived.<br />
<strong>B</strong> Not enough cars were made.<br />
<strong>C</strong> Car companies found them hard to sell.<br />
<strong>D</strong> People found them hard to drive.
</p>

<p style="text-align: justify;">
22. <input type="text" class="${inputClass}" /> When building their first steam car, the Doble brothers<br />
<strong>A</strong> constructed all the parts themselves.<br />
<strong>B</strong> made written notes at each stage of the construction.<br />
<strong>C</strong> needed several attempts to achieve a competitive model.<br />
<strong>D</strong> sought the advice of experienced people in the car industry.
</p>

<p style="text-align: justify;">
23. <input type="text" class="${inputClass}" /> In order to produce the Model C, the Doble brothers<br />
<strong>A</strong> moved production to a different city.<br />
<strong>B</strong> raised financial capital.<br />
<strong>C</strong> employed an additional worker.<br />
<strong>D</strong> abandoned their earlier designs.
</p>

<p style="text-align: justify;"><strong>Questions 24-26</strong><br />Complete the summary below. Choose <strong>ONE WORD AND/ OR A NUMBER</strong> from the passage for each answer. Write your answers in boxes 24-26 on your answer sheet.</p>

<p style="text-align: center;"><strong>The Model E</strong></p>
<p style="text-align: justify;">The Model E was road-tested in 1924 by the Automobile Club of America. They found it easy to drive, despite its weight, and it impressed the spectators. A later version of the Model E raised its (24) <input type="text" class="${inputClass}" /> while keeping its emissions extremely low. The steam car was too expensive for many people and its design was constantly being altered. Under (25) <input type="text" class="${inputClass}" /> cars were produced before the company went out of business. However, even today, there are Model Es on the road in the US. They are straightforward to maintain, and they satisfy California’s (26) <input type="text" class="${inputClass}" /> emissions laws. Perhaps today’s technology and materials would help us revive the steam car.</p>
`
                }}
              />
            )}

            {activeTab === 2 && (
              <div
                dangerouslySetInnerHTML={{
                  __html: `
<p style="text-align: justify;"><strong>Questions 27-30</strong><br />Choose the correct letter, <strong>A, B, C or D</strong>.</p>

<p style="text-align: justify;">
27. <input type="text" class="${inputClass}" /> The writer describes the Romeo and Juliet lesson in order to demonstrate<br />
<strong>A</strong> how few students are interested in literature.<br />
<strong>B</strong> how a teacher handles a range of learning needs.<br />
<strong>C</strong> how unsuitable Shakespeare is for most teenagers.<br />
<strong>D</strong> how weaker students can disrupt their classmates’ learning.
</p>

<p style="text-align: justify;">
28. <input type="text" class="${inputClass}" /> What does the writer say about streaming in the third paragraph?<br />
<strong>A</strong> It has a very broad appeal.<br />
<strong>B</strong> It favours cleverer students.<br />
<strong>C</strong> It is relatively simple to implement.<br />
<strong>D</strong> It works better in some schools than others.
</p>

<p style="text-align: justify;">
29. <input type="text" class="${inputClass}" /> What idea is suggested by the reference to Mount Qomolangma in the fifth paragraph?<br />
<strong>A</strong> students following unsuitable paths<br />
<strong>B</strong> students attempting interesting tasks<br />
<strong>C</strong> students not achieving their full potential<br />
<strong>D</strong> students not being aware of their limitations
</p>

<p style="text-align: justify;">
30. <input type="text" class="${inputClass}" /> What does the word ‘scaffolding’ in the sixth paragraph refer to?<br />
<strong>A</strong> the factors which prevent a student from learning effectively<br />
<strong>B</strong> the environment where most of a student’s learning takes place<br />
<strong>C</strong> the assistance given to a student in their initial stages of learning<br />
<strong>D</strong> the setting of appropriate learning targets for a student’s aptitude
</p>

<p style="text-align: justify;"><strong>Questions 31-35</strong><br />Complete the summary using the list of phrases, A-I, below. Write the correct letter, <strong>A-I</strong>, in boxes 31-35 on your answer sheet.</p>

<p style="text-align: center;"><strong>Is streaming effective?</strong></p>
<p style="text-align: justify;">According to Professor John Hattie of the Melbourne Education Research Institute, there is very little indication that streaming leads to (31) <input type="text" class="${inputClass}" /> He points out that, in schools which use streaming, the most significant impact is on those students placed in the (32) <input type="text" class="${inputClass}" /> , especially where a large proportion of them have (33) <input type="text" class="${inputClass}" /> Meanwhile, for the (34) <input type="text" class="${inputClass}" /> , there appears to be only minimal advantage. A further issue is that teachers tend to have (35) <input type="text" class="${inputClass}" /> of students in streamed groups.</p>

<div class="grid grid-cols-2 sm:grid-cols-3 gap-2 my-4 p-4 bg-slate-50 rounded-xl border border-slate-200 text-sm">
  <div><strong>A</strong> wrong classes</div>
  <div><strong>B</strong> lower expectations</div>
  <div><strong>C</strong> average learners</div>
  <div><strong>D</strong> bottom sets</div>
  <div><strong>E</strong> brightest pupils</div>
  <div><strong>F</strong> disadvantaged backgrounds</div>
  <div><strong>G</strong> weaker students</div>
  <div><strong>H</strong> higher achievements</div>
  <div><strong>I</strong> positive impressions</div>
</div>

<p style="text-align: justify;"><strong>Questions 36-40</strong><br />Do the following statements agree with the views of the writer in reading passage? In boxes 36-40 on your answer sheet, write</p>
<p style="text-align: justify;">
<strong>YES</strong> if the statement agrees with the views of the writer<br />
<strong>NO</strong> if the statement contradicts the views of the writer<br />
<strong>NOT GIVEN</strong> if it is impossible to say what the writer thinks about this
</p>

<p style="text-align: justify;">
36. <input type="text" class="${inputClass}" /> The Vygotsky model of education supports the concept of a mixed-ability class.<br />
37. <input type="text" class="${inputClass}" /> Some teachers are uncertain about allowing students to take on MKO roles in the classroom.<br />
38. <input type="text" class="${inputClass}" /> It can be rewarding to teach knowledge which you have only recently acquired.<br />
39. <input type="text" class="${inputClass}" /> The priority should be to ensure that the highest-achieving students attain their goals.<br />
40. <input type="text" class="${inputClass}" /> Taking part in collaborative outdoor activities with teachers and classmates can improve student outcomes in the classroom.
</p>
`
                }}
              />
            )}

            <div className="mt-12 border-t border-slate-100 pt-8 pb-8">
              <button 
                onClick={() => setShowAnswers(!showAnswers)}
                className="bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white font-semibold py-3 px-8 rounded-xl shadow-md hover:shadow-lg transition-all transform hover:-translate-y-0.5 active:translate-y-0 flex items-center justify-center w-full sm:w-auto"
              >
                {showAnswers ? 'Hide Answers' : 'Show Answers'}
              </button>
              
              {showAnswers && (
                <div className="mt-6 p-6 bg-white rounded-xl shadow-sm border border-slate-200">
                  <h3 className="font-bold text-lg mb-4 text-slate-800">Answers</h3>
                  <div className="grid grid-cols-2 gap-4 text-sm text-slate-700">
                    <div>
                      <p>
                        1. G<br />
                        2. D<br />
                        3. C<br />
                        4. F<br />
                        5. Architects<br />
                        6. Moisture<br />
                        7. Layers<br />
                        8. Speed<br />
                        9. C<br />
                        10. A<br />
                        11. B<br />
                        12. D<br />
                        13. A<br />
                        14. iii<br />
                        15. viii<br />
                        16. vi<br />
                        17. v<br />
                        18. vii<br />
                        19. i<br />
                        20. iv
                      </p>
                    </div>
                    <div>
                      <p>
                        21. A<br />
                        22. C<br />
                        23. B<br />
                        24. Speed<br />
                        25. Fifty/ 50<br />
                        26. Strict<br />
                        27. B<br />
                        28. A<br />
                        29. C<br />
                        30. C<br />
                        31. H<br />
                        32. D<br />
                        33. F<br />
                        34. E<br />
                        35. B<br />
                        36. No<br />
                        37. Not given<br />
                        38. Yes<br />
                        39. No<br />
                        40. Not given
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </section>

        {/* Right Pane: Passages */}
        <section className="w-1/2 relative z-10 bg-white rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-slate-100 flex flex-col overflow-hidden">
          {/* Tabs Header */}
          <div className="flex border-b border-slate-200 bg-slate-50/80 px-4 pt-4 gap-2">
            {[1, 2, 3].map((tabNum, idx) => (
              <button
                key={tabNum}
                onClick={() => setActiveTab(idx)}
                className={`px-6 py-3 rounded-t-lg font-bold text-sm transition-colors border-x border-t ${
                  activeTab === idx 
                    ? 'bg-white border-slate-200 text-blue-700 shadow-sm relative top-[1px]' 
                    : 'bg-transparent border-transparent text-slate-500 hover:text-slate-700 hover:bg-slate-100'
                }`}
              >
                Passage {tabNum}
              </button>
            ))}
          </div>
          
          {/* Tab Content */}
          <div className="p-10 prose prose-slate prose-headings:text-slate-800 prose-p:text-slate-700 prose-p:mb-6 prose-strong:text-slate-700 max-w-none overflow-y-auto scroll-smooth flex-1">
            {activeTab === 0 && (
              <div
                dangerouslySetInnerHTML={{
                  __html: `
<p style="text-align: center;"><strong>Materials to take us beyond concrete</strong></p>
<p style="text-align: center;"><em>Concrete is everywhere, but it’s bad for the planet, generating large amounts of carbon dioxide – alternatives are being developed</em></p>
<p style="text-align: justify;"><strong>A</strong> Concrete is the second most used substance in the global economy, after water – and one of the world’s biggest single sources of greenhouse gas emissions. The chemical process by which cement, the key ingredient of concrete, is created results in large quantities of carbon dioxide. The UN estimates that there will be 9.8 billion people living on the planet by mid-century. They will need somewhere to live. If concrete is the only answer to the construction of new cities, then carbon emissions will soar, aggravating global warming. And so scientists have started innovating with other materials, in a scramble for alternatives to a universal commodity that has underpinned our modern life for many years.</p>
<p style="text-align: justify;"><strong>B</strong> The problem with replacing concrete is that it is so very good at what it does. Chris Cheeseman, an engineering professor at Imperial College London, says the key thing to consider is the extent to which concrete is used around the world, and is likely to continue to be used. ‘Concrete is not a high-carbon product. Cement is high carbon, but concrete is not. But it is the scale on which it is used that makes it high carbon. The sheer scale of manufacture is so huge, that is the issue.’</p>
<p style="text-align: justify;"><strong>C</strong> Not only are the ingredients of concrete relatively cheap and found in abundance in most places around the globe, the stuff itself has marvellous properties: Portland cement, the vital component of concrete, is mouldable and pourable, but quickly sets hard. Cheeseman also notes another advantage: concrete and steel have similar thermal expansion properties, so steel can be used to reinforce concrete, making it far stronger and more flexible as a building material than it could be on its own. According to Cheeseman, all these factors together make concrete hard to beat. ‘Concrete is amazing stuff. Making anything with similar properties is going to be very difficult.’</p>
<p style="text-align: justify;"><strong>D</strong> A possible alternative to concrete is wood. Making buildings from wood may seem like a rather medieval idea, but climate change is driving architects to turn to treated timber as a possible resource. Recent years have seen the emergence of tall buildings constructed almost entirely from timber. Vancouver, Vienna and Brumunddal in Norway are all home to constructed tall, wooden buildings.</p>
<p style="text-align: justify;"><strong>E</strong> Using wood to construct buildings, however, is not straightforward. Wood expands as it absorbs moisture from the air and is susceptible to pests, not to mention fire. But treating wood and combining it with other materials can improve its properties. Cross-laminated timber is engineered wood. An adhesive is used to stick layers of solid-sawn timber together, crosswise, to form building blocks. This material is light but has the strength of concrete and steel. Construction experts say that wooden buildings can be constructed at a greater speed than ones of concrete and steel and the process, it seems, is quieter.</p>
<p style="text-align: justify;"><strong>F</strong> Stora Enso is Europe’s biggest supplier of cross-laminated timber, and its vice-president Markus Mannstrom reports that the company is seeing increasing demand globally for building in wood, with climate change concerns the key driver. Finland, with its large forests, where Stora Enso is based, has been leading the way, but the company is seeing a rise in demand for its timber products across the world, including in Asia. Of course, using timber in a building also locks away the carbon that it absorbed as it grew. But even treated wood has its limitations and only when a wider range of construction projects has been proven in practice will it be possible to see wood as a real alternative to concrete in constructing tall buildings.</p>
<p style="text-align: justify;"><strong>G</strong> Fly ash and slag from iron ore are possible alternatives to cement in a concrete mix. Fly ash, a byproduct of coal-burning power plants, can be incorporated into concrete mixes to make up as much as 15 to 30% of the cement, without harming the strength or durability of the resulting mix. Iron-ore slag, a byproduct of the iron-ore smelting process, can be used in a similar way. Their incorporation into concrete mixes has the potential to reduce greenhouse gas emissions. But Anna Surgenor, of the UK’s Green Building Council, notes that although these waste products can save carbon in the concrete mix, their use is not always straightforward. ‘It’s possible to replace the cement content in concrete with waste products to lower the overall carbon impact. But there are several calculations that need to be considered across the entire life cycle of the building – these include factoring in where these materials are being shipped from. If they are transported over long distances, using fossil fuels, the use of alternative materials might not make sense from an overall carbon reduction perspective.’</p>
<p style="text-align: justify;"><strong>H</strong> While these technologies are all promising ideas, they are either unproven or based on materials that are not abundant. In their overview of innovation in the concrete industry, Felix Preston and Johanna Lehne of the UK’s Royal Institute of International Affairs reached the conclusion that, ‘Some novel cements have been discussed for more than a decade within the research community, without breaking through. At present, these alternatives are rarely as cost-effective as conventional cement, and they face raw-material shortages and resistance from customers.’</p>
`
                }}
              />
            )}

            {activeTab === 1 && (
              <div
                dangerouslySetInnerHTML={{
                  __html: `
<p style="text-align: center;"><strong>The steam car</strong></p>
<p style="text-align: justify;"><strong>A</strong> When primitive automobiles first began to appear in the 1800s, their engines were based on steam power. Steam had already enjoyed a long and successful career in the railways, so it was only natural that the technology evolved into a miniaturized version which was separate from the trains. But these early cars inherited steam’s weaknesses along with its strengths. The boilers had to be lit by hand, and they required about twenty minutes to build up pressure before they could be driven. Furthermore, their water reservoirs only lasted for about thirty miles before needing replenishment. Despite such shortcomings, these newly designed self-propelled carriages offered quick transportation, and by the early 1900s it was not uncommon to see such machines shuttling wealthy citizens around town.</p>
<p style="text-align: justify;"><strong>B</strong> But the glory days of steam cars were few. A new technology called the Internal Combustion Engine soon appeared, which offered the ability to drive down the road just moments after starting up. At first, these noisy gasoline cars were unpopular because they were more complicated to operate and they had difficult hand-crank starters, which were known to break arms when the engines backfired. But in 1912 General Motors introduced the electric starter, and over the following few years steam power was gradually phased out.</p>
<p style="text-align: justify;"><strong>C</strong> Even as the market was declining, four brothers made one last effort to rekindle the technology. Between 1906 and 1909, while still attending high school, Abner Doble and his three brothers built their first steam car in their parents’ basement. It comprised parts taken from a wrecked early steam car but reconfigured to drive an engine of their own design. Though it did not run well, the Doble brothers went on to build a second and third prototype in the following years. Though the Doble boys’ third prototype, nicknamed the Model B, still lacked the convenience of an internal combustion engine, it drew the attention of automobile trade magazines due to its numerous improvements over previous steam cars. The Model B proved to be superior to gasoline automobiles in many ways. Its high-pressure steam drove the engine pistons in virtual silence, in contrast to clattering gas engines which emitted the aroma of burned hydrocarbons. Perhaps most impressively, the Model B was amazingly swift. It could accelerate from zero to sixty miles per hour in just fifteen seconds, a feat described as ‘remarkable acceleration’ by Automobile magazine in 1914.</p>
<p style="text-align: justify;"><strong>D</strong> The following year Abner Doble drove the Model B from Massachusetts to Detroit in order to seek investment in his automobile design, which he used to open the General Engineering Company. He and his brothers immediately began working on the Model C, which was intended to expand upon the innovations of the Model B. The brothers added features such as a key-based ignition in the cabin, eliminating the need for the operator to manually ignite the boiler. With these enhancements, the Dobles’ new car company promised a steam vehicle which would provide all of the convenience of a gasoline car, but with much greater speed, much simpler driving controls, and a virtually silent powerplant. By the following April, the General Engineering Company had received 5,390 deposits for Doble Detroits, which were scheduled for delivery in early 1918.</p>
<p style="text-align: justify;"><strong>E</strong> Later that year Abner Doble delivered unhappy news to those eagerly awaiting the delivery of their modern new cars. Those buyers who received the handful of completed cars complained that the vehicles were sluggish and erratic, sometimes going in reverse when they should go forward. The new engine design, though innovative, was still plagued with serious glitches.</p>
<p style="text-align: justify;"><strong>F</strong> The brothers made one final attempt to produce a viable steam automobile. In early 1924, the Doble brothers shipped a Model E to New York City to be road-tested by the Automobile Club of America. After sitting overnight in freezing temperatures, the car was pushed out into the road and left to sit for over an hour in the frosty morning air. At the turn of the key, the boiler lit and reached its operating pressure inside of forty seconds. As they drove the test vehicle further, they found that its evenly distributed weight lent it surprisingly good handling, even though it was so heavy. As the new Doble steamer was further developed and tested, its maximum speed was pushed to over a hundred miles per hour, and it achieved about fifteen miles per gallon of kerosene with negligible emissions.</p>
<p style="text-align: justify;"><strong>G</strong> Sadly, the Dobles’ brilliant steam car never was a financial success. Priced at around $18,000 in 1924, it was popular only among the very wealthy. Plus, it is said that no two Model Es were quite the same, because Abner Doble tinkered endlessly with the design. By the time the company folded in 1931, fewer than fifty of the amazing Model E steam cars had been produced. For his whole career, until his death in 1961, Abner Doble remained adamant that steam-powered automobiles were at least equal to gasoline cars, if not superior. Given the evidence, he may have been right. Many of the Model E Dobles which have survived are still in good working condition, some having been driven over half a million miles with only normal maintenance. Astonishingly, an unmodified Doble Model E runs clean enough to pass the emissions laws in California today, and they are pretty strict. It is true that the technology poses some difficult problems, but you cannot help but wonder how efficient a steam car might be with the benefit of modern materials and computers. Under the current pressure to improve automotive performance and reduce emissions, it is not unthinkable that the steam car may rise again.</p>
`
                }}
              />
            )}

            {activeTab === 2 && (
              <div
                dangerouslySetInnerHTML={{
                  __html: `
<p style="text-align: center;"><strong>The case for mixed-ability classes</strong></p>
<p style="text-align: justify;">Picture this scene. It’s an English literature lesson in a UK school, and the teacher has just read an extract from Shakespeare’s Romeo and Juliet with a class of 15-year-olds. He’s given some of the students copies of No Fear Shakespeare, a kid-friendly translation of the original. For three students, even these literacy demands are beyond them. Another girl simply can’t focus and he gives her pens and paper to draw with. The teacher can ask the No Fear group to identify the key characters and maybe provide a tentative plot summary. He can ask most of the class about character development, and five of them might be able to support their statements with textual evidence. Now two curious students are wondering whether Shakespeare advocates living a life of moderation or one of passionate engagement.</p>
<p style="text-align: justify;">As a teacher myself, I’d think my lesson would be going rather well if the discussion went as described above. But wouldn’t this kind of class work better if there weren’t such a huge gap between the top and the bottom? If we put all the kids who needed literacy support into one class, and all the students who want to discuss the virtue of moderation into another?</p>
<p style="text-align: justify;">The practice of ‘streaming’, or ‘tracking’, involves separating students into classes depending on their diagnosed levels of attainment. At a macro level, it requires the establishment of academically selective schools for the brightest students, and comprehensive schools for the rest. Within schools, it means selecting students into a ‘stream’ of general ability, or ‘sets’ of subject-specific ability. The practice is intuitively appealing to almost every stakeholder.</p>
<p style="text-align: justify;">I have heard the mixed-ability model attacked by way of analogy: a group hike. The fittest in the group take the lead and set a brisk pace, only to have to stop and wait every 20 minutes. This is frustrating, and their enthusiasm wanes. Meanwhile, the slowest ones are not only embarrassed but physically struggling to keep up. What’s worse, they never get a long enough break. They honestly just want to quit. Hiking, they feel, is not for them.</p>
<p style="text-align: justify;">Mixed-ability classes bore students, frustrate parents and bum out teachers. The brightest ones will never summit Mount Qomolangma, and the stragglers won’t enjoy the lovely stroll in the park they are perhaps more suited to. Individuals suffer at the demands of the collective, mediocrity prevails. So: is learning like hiking?</p>
<p style="text-align: justify;">The current pedagogical paradigm is arguably that of constructivism, which emerged out of the work of psychologist Lev Vygotsky. In the 1930s, Vygotsky emphasised the importance of targeting a student’s specific ‘zone of proximal development’ (ZPD). This is the gap between what they can achieve only with support – teachers, textbooks, worked examples, parents and so on – and what they can achieve independently. The purpose of teaching is to provide and then gradually remove this ‘scaffolding’ until they are autonomous. If we accept this model, it follows that streaming students with similar ZPDs would be an efficient and effective solution. And that forcing everyone on the same hike – regardless of aptitude – would be madness.</p>
<p style="text-align: justify;">Despite all this, there is limited empirical evidence to suggest that streaming results in better outcomes for students. Professor John Hattie, director of the Melbourne Education Research Institute, notes that ‘tracking has minimal effects on learning outcomes’. What is more, streaming appears to significantly – and negatively – affect those students assigned to the lowest sets. These students tend to have much higher representation of low socioeconomic class. Less significant is the small benefit for those lucky clever students in the higher sets. The overall result is that the smart stay smart and the dumb get dumber, further entrenching the social divide.</p>
<p style="text-align: justify;">In the latest update of Hattie’s influential meta-analysis of factors influencing student achievement, one of the most significant factors is the teachers’ estimate of achievement. Streaming students by diagnosed achievement automatically limits what the teacher feels the student is capable of. Meanwhile, in a mixed environment, teachers’ estimates need to be more diverse and flexible.</p>
<p style="text-align: justify;">While streaming might seem to help teachers effectively target a student’s ZPD, it can underestimate the importance of peer-to-peer learning. A crucial aspect of constructivist theory is the role of the MKO – ‘more-knowledgeable other’ – in knowledge construction. While teachers are traditionally the MKOs in classrooms, the value of knowledgeable student peers must not go unrecognised either.</p>
<p style="text-align: justify;">I find it amazing to watch students get over an idea to their peers in ways that I would never think of. They operate with different language tools and different social tools from teachers and, having just learnt it themselves, they possess similar cognitive structures to their struggling classmates. There is also something exciting about passing on skills and knowledge that you yourself have just mastered – a certain pride and zeal, a certain freshness to the interaction between ‘teacher’ and ‘learner’ that is often lost by the expert for whom the steps are obvious and the joy of discovery forgotten.</p>
<p style="text-align: justify;">Having a variety of different abilities in a collaborative learning environment provides valuable resources for helping students meet their learning needs, not to mention improving their communication and social skills. And today, more than ever, we need the many to flourish – not suffer at the expense of a few bright stars. Once a year, I go on a hike with my class, a mixed bunch of students. It is challenging. The fittest students realise they need to encourage the reluctant. There are lookouts who report back, and extra items to carry for others. We make it – together.</p>
`
                }}
              />
            )}
          </div>
        </section>
      </main>
    </div>
  );
}
